services:
  db:
    image: postgres:15
    container_name: papyrus_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papyrus_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
